server:
  port: ${PORT:8088}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    stream:
      binders:
        heroku_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${AMQP_HOST}
                port: 5672
                username: ${AMQP_USER}
                password: ${AMQP_PASSWORD}
                virtual-host: ${AMQP_USER}
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: WARN
authorization:
  token: ${TOKEN}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8084}/eureka/
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    secure-port-enabled: false
    non-secure-port-enabled: true
    secure-port: 443
    non-secure-port: 80
  password: ${EUREKA_PASSWORD:password}
ribbon:
  eager-load:
    enabled: true
security:
  user:
    password: ${eureka.password}
---
spring:
  profiles: local
eureka:
  instance:
    homePageUrl: http://${eureka.instance.hostname}:8088/
    non-secure-port: 8088
app:
  base-url: ${APP_HOST:http://localhost:8080}
scheduling:
  enabled: true
