server:
  port: ${PORT:8088}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    stream:
      binders:
        heroku_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${AMQP_HOST}
                port: 5672
                username: ${AMQP_USER}
                password: ${AMQP_PASSWORD}
                virtual-host: ${AMQP_USER}
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: WARN
authorization:
  token: ${TOKEN}
ribbon:
  eager-load:
    enabled: true
app:
  base-url: ${APP_HOST:http://localhost:8080}
