databaseChangeLog:
- changeSet:
    id: 1570039936946-1
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: email_verificationPK
            name: id
            type: BIGINT
        - column:
            name: created_date
            type: TIMESTAMP WITHOUT TIME ZONE
        - column:
            name: email
            type: VARCHAR(255)
        - column:
            name: verification_id
            type: VARCHAR(255)
        tableName: email_verification
- changeSet:
    id: 1570039936946-2
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: userPK
            name: id
            type: BIGINT
        - column:
            name: account_non_expired
            type: BOOLEAN
        - column:
            name: account_non_locked
            type: BOOLEAN
        - column:
            name: credentials_non_expired
            type: BOOLEAN
        - column:
            name: current_profile_id
            type: BIGINT
        - column:
            name: email
            type: VARCHAR(255)
        - column:
            name: enabled
            type: BOOLEAN
        - column:
            name: password
            type: VARCHAR(255)
        - column:
            name: time_zone
            type: VARCHAR(255)
        tableName: user
- changeSet:
    id: 1570039936946-3
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: user_id
            type: BIGINT
        - column:
            name: roles
            type: VARCHAR(255)
        tableName: user_roles
- changeSet:
    id: 1570039936946-4
    author: albvs (generated)
    changes:
    - addUniqueConstraint:
        columnNames: email
        constraintName: UC_USEREMAIL_COL
        tableName: user
- changeSet:
    id: 1570039936946-5
    author: albvs (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: user_id
        baseTableName: user_roles
        constraintName: FK55itppkw3i07do3h7qoclqd4k
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: user
        validate: true

